CREATE DATABASE EMPLOYEE;
USE EMPLOYEE ;
CREATE TABLE DEPARTMENTS (
       DEPARTMENT_ID INT PRIMARY KEY,
       NAME VARCHAR(100) NOT NULL
       );
CREATE TABLE EMPLOYEES (
       EMPLOYEE_ID INT PRIMARY KEY,
       NAME VARCHAR(50) UNIQUE,
       GENDER ENUM('M','F'),
       AGE INT CHECK (AGE>=18),
       HIRE_DATE DATE DEFAULT(CURRENT_DATE),
       DESIGNATION VARCHAR(100),
       DEPARTMENT_ID INT,
       LOCATION_ID INT,
       SALARY DECIMAL(10,2),
       FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
       FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
       );
 CREATE TABLE LOCATION (
       LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
       LOCATION VARCHAR(100) UNIQUE
       );
       
ALTER TABLE EMPLOYEES ADD COLUMN EMAIL VARCHAR(50) ; 
ALTER TABLE EMPLOYEES MODIFY COLUMN DESIGNATION VARCHAR(150) ;
ALTER TABLE EMPLOYEES DROP COLUMN AGE; 
ALTER TABLE EMPLOYEES RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;
RENAME TABLE DEPARTMENTS TO DEPARTMENT_INFO ;
RENAME TABLE LOCATION TO LOCATIONS ;
TRUNCATE TABLE EMPLOYEES ;
DROP TABLE EMPLOYEES ;
DROP DATABASE EMPLOYEE; 

       










       
       
 
       
	
    



